version: "2"         # required to adjust maintainability checks

plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: false
      allow_strong_copyleft: false
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-10-0

